version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: agency_monitor_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: agency_monitor_api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
    container_name: agency_monitor_dashboard
    depends_on:
      - api
    env_file:
      - .env
    ports:
      - "8501:8501"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    container_name: agency_monitor_worker
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: tail -f /dev/null  # Keeps container running for exec

volumes:
  postgres_data: