version: '3.8'

services:
  api:
    restart: always
    environment:
      - LOG_LEVEL=INFO
    # Use Uvicorn with workers for production performance
    command: uvicorn --workers 4 --host 0.0.0.0 --port 8000 api.main:app

  dashboard:
    restart: always
    environment:
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=none
      - STREAMLIT_SERVER_RUN_ON_SAVE=false
      - STREAMLIT_SERVER_HEADLESS=true