# Configuration for ETL ingestion scripts in the Agency Monitor project.
# Defines sources, countries, indicators, file paths, and versions.
# Structure: Indicators as list of dicts with source_key, code, name, domain, normalization, validation (value_range, type).
# Paths use DATA_ROOT env var (e.g., /data/raw). Update paths after downloading files.
# Updated to latest versions as of July 24, 2025 (V-Dem v15, Freedom House 2025, UNDP HDR 2025).
# Config version for traceability in CI/CD pipelines.
config_version: "1.0.0"

# Section for the World Bank API Ingestion (Task 1.2)
world_bank:
  countries: ["USA", "HTI"]
  indicators:
    - code: "NY.GDP.MKTP.CD"
      name: "GDP (current US$)"
      value_range: {min: 0, max: 1e14}
    - code: "NY.GDP.PCAP.CD"
      name: "GDP per capita (current US$)"
      value_range: {min: 0, max: 1e6}
    - code: "SL.UEM.TOTL.ZS"
      name: "Unemployment, total (% of total labor force) (modeled ILO estimate)"
      value_range: {min: 0, max: 100}
    - code: "SI.POV.GINI"
      name: "Gini index"
      value_range: {min: 0, max: 100}
    - code: "SP.DYN.LE00.IN"
      name: "Life expectancy at birth, total (years)"
      value_range: {min: 0, max: 100}
    - code: "SP.DYN.IMRT.IN"
      name: "Mortality rate, infant (per 1,000 live births)"
      value_range: {min: 0, max: 1000}
    - code: "SH.XPD.GHED.GD.ZS"
      name: "Domestic general government health expenditure (% of GDP)"
      value_range: {min: 0, max: 100}
    - code: "SE.ADT.LITR.ZS"
      name: "Literacy rate, adult total (% of people ages 15 and above)"
      value_range: {min: 0, max: 100}
    - code: "SE.XPD.TOTL.GD.ZS"
      name: "Government expenditure on education, total (% of GDP)"
      value_range: {min: 0, max: 100}

# Section for Bulk Data Ingestion (Task 1.3)
vdem:
  file_path: data/raw/V-Dem-CY-Full+Others-v15.csv
  dataset_version: v15
  indicators:
    - v2x_polyarchy
    - v2x_libdem
    - v2x_partipdem
    - v2x_delibdem
    - v2x_egaldem
    - v2x_freexp_altinf
    - v2x_frassoc_thick
    - v2x_suffr
    - v2x_elecoff
    - v2xcl_rol
    - v2x_cspart
    - v2pepwrsoc
    - v2clprptyw  # Corrected from v2pepwreco; this is women's property rights (economic rights proxy)
    - v2xpe_exlsocgr  # Corrected from v2xpe_exlsoc; exclusion by socio-economic group
    - v2xpe_exlpol
    - v2x_egal
    - v2xpe_exlgeo
etl:
  chunksize: 10000
  countries:
    - USA
    - HTI

freedom_house:
  file_path: "${DATA_ROOT}/All Data, FIW 2013-2024 (Excel Download).xlsx"
  dataset_version: "FIW-2024"
  source_name: "Freedom-House"
  sheet_name: "All Data"
  countries:
    - USA
    - HTI
  indicators:
    - source_key: PR
      code: FH_POLITICAL_RIGHTS
      name: "Political Rights Score"
      domain: political
      type: numeric
      value_range: {min: 0, max: 40}
      normalization: {max: 40}
    - source_key: CL
      code: FH_CIVIL_LIBERTIES
      name: "Civil Liberties Score"
      domain: political
      type: numeric
      value_range: {min: 0, max: 60}
      normalization: {max: 60}

undp:
  file_path: "${DATA_ROOT}/UNDP_Human_Development_Report_2025.csv"
  dataset_version: "UNDP-HDR-2025"
  source_name: "UNDP"
  countries:
    - USA
    - HTI
  indicators:
    - source_key: "Mean years of schooling, adults (years) (ages 25 and older)"
      code: UNDP_MEAN_YEARS_SCHOOLING
      name: "Mean Years of Schooling"
      domain: educational
      type: numeric
      value_range: {min: 0, max: 20}

transparency_international:
  file_path: "${DATA_ROOT}/CPI_2025.csv"
  dataset_version: "CPI-2025"
  source_name: "Transparency-International"
  countries:
    - USA
    - HTI
  indicators:
    - source_key: CPI
      code: TI_CORRUPTION_PERCEPTION
      name: "Corruption Perceptions Index"
      domain: social
      type: numeric
      value_range: {min: 0, max: 100}

# Model configuration for training
models:
  directory: "models"
  hybrid_forecaster:
    max_lags: 3
    xgb_params:
      max_depth: 6
      learning_rate: 0.1
      n_estimators: 100

# Global Validation Section
validation:
  min_year: 1990
  max_year: 2025
  required_countries: [USA, HTI]

database:
  url: postgresql://caseyrobbins@localhost/agency_monitor