ingestion:
  target_countries: ["USA", "HTI", "CHL"]
  world_bank:
    indicators:
      - code: "NY.GDP.PCAP.CD"
        name: "GDP per capita (current US$)"
        domain: "economic"
      - code: "SL.UEM.TOTL.ZS"
        name: "Unemployment, total (% of total labor force)"
        domain: "economic"
      - code: "SP.DYN.LE00.IN"
        name: "Life expectancy at birth, total (years)"
        domain: "health"
      - code: "SE.ADT.LITR.ZS"
        name: "Literacy rate, adult total (% of people ages 15 and above)"
        domain: "educational"
normalization_stats:
  NY.GDP.PCAP.CD:
    p25: 1000
    p75: 50000
    mean: 15000
    std: 10000
  SL.UEM.TOTL.ZS:
    p25: 3
    p75: 15
    mean: 7
    std: 4
  SP.DYN.LE00.IN:
    p25: 60
    p75: 80
    mean: 70
    std: 5
  SE.ADT.LITR.ZS:
    p25: 70
    p75: 98
    mean: 85
    std: 12
paths:
  validation_cases_path: data/validation_cases.json
  validation_report_path: reports/validation_report.json
models:
  directory: "models"
  hybrid_forecaster:
    max_lags: 10
    xgb_params:
      n_estimators: 300
      max_depth: 6
      learning_rate: 0.05
      subsample: 0.8
      colsample_bytree: 0.7
      gamma: 0.1
      reg_alpha: 0.1
      reg_lambda: 1.0
      random_state: 42
      n_jobs: -1
features:
  shock_penalty_scale: 2.0
  windows:
    short: 3
    medium: 7
    long: 15
nlp:
  confidence_threshold: 0.5
  normalization: density
  max_chunk_length: 512
  min_chunk_length: 25